# Configuration

bbmri_structure_definition_url: "https://fhir.bbmri.de/StructureDefinition"
# Server URL
server_url: "http://localhost:8080/fhir"

# Biobank info 
biobank_id: "0000001234"
biobank_name: "Biobanca Di Ricerca BBDATA"

biobank_alias:
  - "BB-BBDATA"

biobank_contact:

  - address:
      use: "work"
      type: "physical"
      country: "IT"
      city: "Rome"
      postalCode: "00161"
      line:
        - "Viale Manzoni"

    telecom:
      - system: "phone"
        value: "+395453534534"
        use: "work"
        rank: 1

      - system: "email"
        value: "pippo.baudo@isnt.it"
        use: "work"
        rank: 1


# Collection info 
collection_id: "123456789"
collection_name: "XX Diseases"

collection_alias:

collection_contact:

  - address:
      use: "work"
      type: "physical"
      country: "IT"
      city: "Rome"
      postalCode: "00161"
      line:
        - "Viale Manzoni"

    telecom:

      - system: "phone"
        value: "+395453534534"
        use: "work"
        rank: 1

      - system: "email"
        value: "pippo.baudo@isnt.it"
        use: "work"
        rank: 1


