bbmri_structure_definition_url: "https://fhir.bbmri.de/StructureDefinition"
server_url: "http://example.com"

# Collection info 
collection_id: "1606752281669494"
collection_name: "Colorectal Cancer Collection"

collection_alias:
  - "CRC"

collection_contact:

  - address:
      use: "work"
      type: "physical"
      country: "IT"
      city: "Rome"
      postalCode: "00123"
      line:
        - "Via Manzoni 35"

    telecom:

      - system: "phone"
        value: "+395453534534"
        use: "work"
        rank: 1

      - system: "email"
        value: "pippo.baudo@isnt.it"
        use: "work"
        rank: 1

# Biobank info 
biobank_id: "1606752281669494"
biobank_name: "Istituto Nazionale Tumori Regina Elena"

biobank_alias:
  - "IRE"

biobank_contact:

  - address:
      use: "work"
      type: "physical"
      country: "IT"
      city: "Rome"
      postalCode: "00123"
      line:
        - "Via Chianesi 35"

    telecom:

      - system: "phone"
        value: "+395453534534"
        use: "work"
        rank: 1

      - system: "email"
        value: "pippo.baudo@isnt.it"
        use: "work"
        rank: 1

